<script lang="ts">
    import { Trash } from "phosphor-svelte";
    import type { Row, RowField, ColumnInfo, Value } from "../types.js";
    import { Button } from "../lib/components/ui/index.js";
    import { Input } from "../lib/components/ui/index.js";
    import { NumberInput } from "../lib/components/ui/index.js";
    import { DatetimeInput } from "../lib/components/ui/index.js";
    import { Textarea } from "../lib/components/ui/index.js";
    import { Checkbox } from "../lib/components/ui/index.js";
    import { Label } from "../lib/components/ui/index.js";
    import { Dialog } from "../lib/components/ui/index.js";

    interface Props {
        columns: ColumnInfo[];
        row: Row | null; // null = creating new row
        onSave: (data: Row) => void;
        onDelete?: () => void;
        onClose: () => void;
        saving?: boolean;
        deleting?: boolean;
    }

    let {
        columns,
        row,
        onSave,
        onDelete,
        onClose,
        saving = false,
        deleting = false,
    }: Props = $props();

    // Form state - map column name to string value
    let formValues = $state<Map<string, string>>(new Map());

    // Initialize form values from row or empty
    $effect(() => {
        const newValues = new Map<string, string>();
        for (const col of columns) {
            if (row) {
                const field = row.fields.find((f) => f.name === col.name);
                if (field) {
                    newValues.set(col.name, valueToString(field.value));
                } else {
                    newValues.set(col.name, "");
                }
            } else {
                newValues.set(col.name, "");
            }
        }
        formValues = newValues;
    });

    function valueToString(value: Value): string {
        if (value.tag === "Null") return "";
        if (typeof value.value === "bigint") return value.value.toString();
        if (value.tag === "Bytes") return "<bytes>";
        if (value.tag === "Bool") return value.value ? "true" : "false";
        return String(value.value);
    }

    function stringToValue(str: string, sqlType: string): Value {
        const typeLower = sqlType.toLowerCase();

        if (str === "") {
            return { tag: "Null" };
        }

        if (typeLower.includes("bool")) {
            return { tag: "Bool", value: str.toLowerCase() === "true" || str === "1" };
        }

        if (typeLower.includes("int8") || typeLower === "bigint" || typeLower === "bigserial") {
            return { tag: "I64", value: BigInt(str) };
        }

        if (typeLower.includes("int4") || typeLower === "integer" || typeLower === "serial") {
            return { tag: "I32", value: parseInt(str, 10) };
        }

        if (typeLower.includes("int2") || typeLower === "smallint" || typeLower === "smallserial") {
            return { tag: "I16", value: parseInt(str, 10) };
        }

        if (typeLower.includes("float4") || typeLower === "real") {
            return { tag: "F32", value: parseFloat(str) };
        }

        if (
            typeLower.includes("float8") ||
            typeLower === "double precision" ||
            typeLower.includes("numeric") ||
            typeLower.includes("decimal")
        ) {
            return { tag: "F64", value: parseFloat(str) };
        }

        return { tag: "String", value: str };
    }

    function handleSave() {
        const fields: RowField[] = [];
        for (const col of columns) {
            // Skip auto-generated fields when creating
            if (!row && isAutoGenerated(col)) continue;

            const strValue = formValues.get(col.name) ?? "";
            fields.push({
                name: col.name,
                value: stringToValue(strValue, col.sql_type),
            });
        }
        onSave({ fields });
    }

    function handleDelete() {
        if (onDelete && confirm("Are you sure you want to delete this row?")) {
            onDelete();
        }
    }

    function getFormValue(colName: string): string {
        return formValues.get(colName) ?? "";
    }

    function setFormValue(colName: string, value: string) {
        formValues = new Map(formValues).set(colName, value);
    }

    function isPrimaryKey(col: ColumnInfo): boolean {
        return col.primary_key;
    }

    function isAutoGenerated(col: ColumnInfo): boolean {
        const def = col.default?.toLowerCase() ?? "";
        return (
            def.includes("nextval") ||
            def.includes("gen_random_uuid") ||
            def.includes("now()") ||
            def.includes("current_timestamp")
        );
    }

    // Determine what type of control to use for a column
    function getControlType(col: ColumnInfo): "checkbox" | "number" | "datetime" | "textarea" | "text" {
        const typeLower = col.sql_type.toLowerCase();

        if (typeLower.includes("bool")) {
            return "checkbox";
        }

        if (
            typeLower.includes("timestamp") ||
            typeLower.includes("datetime")
        ) {
            return "datetime";
        }

        if (
            typeLower.includes("int") ||
            typeLower.includes("serial") ||
            typeLower.includes("float") ||
            typeLower.includes("numeric") ||
            typeLower.includes("decimal") ||
            typeLower.includes("real") ||
            typeLower === "double precision"
        ) {
            return "number";
        }

        if (typeLower === "text" || typeLower.includes("json")) {
            return "textarea";
        }

        return "text";
    }

    function getBooleanValue(colName: string): boolean {
        const val = getFormValue(colName);
        return val.toLowerCase() === "true" || val === "1";
    }

    function setBooleanValue(colName: string, checked: boolean) {
        setFormValue(colName, checked ? "true" : "false");
    }
</script>

<Dialog open={true} {onClose} title={row ? "Edit Row" : "Create Row"}>
    <div class="space-y-4">
        {#each columns as col}
            {@const isAuto = isAutoGenerated(col)}
            {@const isPK = isPrimaryKey(col)}
            {@const hideOnCreate = !row && isAuto}
            {@const disabled = row && isPK}
            {@const controlType = getControlType(col)}

            {#if hideOnCreate}
                <!-- Skip auto-generated fields when creating -->
            {:else}

            <div class="space-y-1.5">
                <div>
                    <div class="flex items-center gap-2">
                        <Label for={col.name}>{col.name}</Label>
                        <span class="text-[10px] text-neutral-600">{col.sql_type}</span>
                        {#if isPK}
                            <span class="text-[10px] text-neutral-500">pk</span>
                        {/if}
                    </div>
                    {#if col.doc}
                        <p class="text-xs text-neutral-500">{col.doc}</p>
                    {/if}
                </div>

                {#if controlType === "checkbox"}
                    <div class="flex items-center gap-3 h-9">
                        <Checkbox
                            id={col.name}
                            checked={getBooleanValue(col.name)}
                            onchange={(checked) => setBooleanValue(col.name, checked)}
                            {disabled}
                        />
                        <span class="text-sm text-neutral-500">
                            {getBooleanValue(col.name) ? "true" : "false"}
                        </span>
                    </div>
                {:else if controlType === "number"}
                    <NumberInput
                        id={col.name}
                        value={getFormValue(col.name)}
                        oninput={(e) => setFormValue(col.name, e.currentTarget.value)}
                        placeholder={col.nullable ? "null" : ""}
                        {disabled}
                    />
                {:else if controlType === "datetime"}
                    <DatetimeInput
                        id={col.name}
                        value={getFormValue(col.name)}
                        onchange={(v) => setFormValue(col.name, v)}
                        {disabled}
                    />
                {:else if controlType === "textarea"}
                    <Textarea
                        id={col.name}
                        value={getFormValue(col.name)}
                        oninput={(e) => setFormValue(col.name, e.currentTarget.value)}
                        placeholder={col.nullable ? "null" : ""}
                        disabled={disabled || false}
                        rows={3}
                    />
                {:else}
                    <Input
                        id={col.name}
                        type="text"
                        value={getFormValue(col.name)}
                        oninput={(e) => setFormValue(col.name, e.currentTarget.value)}
                        placeholder={col.nullable ? "null" : ""}
                        {disabled}
                    />
                {/if}
            </div>
            {/if}
        {/each}
    </div>

    {#snippet footer()}
        {#if row && onDelete}
            <div class="mr-auto">
                <Button variant="destructive" onclick={handleDelete} disabled={deleting}>
                    <Trash size={16} />
                    {deleting ? "Deleting..." : "Delete"}
                </Button>
            </div>
        {/if}
        <Button variant="outline" onclick={onClose} disabled={saving || deleting}>Cancel</Button>
        <Button onclick={handleSave} disabled={saving || deleting}>
            {saving ? "Saving..." : "Save"}
        </Button>
    {/snippet}
</Dialog>
